Vega/Vegumbr/Vegumbr/Models/CommentViewModel.cs
using System;

namespace Vegumbr.Models
{
    public class CommentViewModel 
    {
        public Guid Id { get; set; }

        public string Author { get; set; }

        public string Message { get; set; }

        public int PostId { get; set; }

        public bool Published { get; set; }

        public DateTime CreateDate { get; set; }

        public int UmbracoId { get; set; }

        public int DocumentType { get; set; }

        public int UmbracoMemberId { get; set; }
    }
}

Vega/Vegumbr/Vegumbr/Controllers/CommentController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Umbraco.Core.Models;
using Umbraco.Core.Persistence;
using Umbraco.Core.Security;
using Umbraco.Core.Services;
using Umbraco.Web.Mvc;
using Vega.BLL.Contracts.Services;
using Vegumbr.Models;
using Umbraco.Core;

namespace Vegumbr.Controllers
{
    public class CommentController : SurfaceController
    {
        public const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/";

        private readonly ICommentService commentService;

        private readonly int CurrentMemberId = umbraco.cms.businesslogic.member.Member.CurrentMemberId();
        private readonly string CurrentUserName = CustomRoleProvider.GetCurrentUser().FirstOrDefault().ToString()??null;

        public CommentController(ICommentService _commentService)
        {
            commentService = _commentService;
        }

        [HttpPost]
        public ActionResult Submit(CommentViewModel model)
        {
            //var ticket = new System.Web.HttpContextWrapper(System.Web.HttpContext.Current).GetUmbracoAuthTicket();
            //if (ticket != null)
            //{
            //    //var user = Umbraco.Core.ApplicationContext.Current.Services.UserService.GetByUsername(ticket.Name);
            //}
            //var member = Services.MemberService.GetByUsername("qq@mail.com");

            model.Author = CurrentUserName;
            model.UmbracoMemberId = CurrentMemberId;
            commentService.Create(Mapper.Mapper.ToDto(model));
            return PartialView(PARTIAL_VIEW_FOLDER + "_SuccessAlert.cshtml");
        }

        public ActionResult GetCommentsByPost(int id)
        {
            var publishedItems = commentService.GetPublishedByPost(id).Select(Mapper.Mapper.ToEntity);
            var CurrentUserName1 = CustomRoleProvider.GetCurrentUser().First().ToString();
            return PartialView(PARTIAL_VIEW_FOLDER + "_CommentsListPartial.cshtml", publishedItems);
        }

        public ActionResult Delete(Guid id, int parentId, int umbracoId)
        {
            IContentService service = ApplicationContext.Services.ContentService;

            IContent comment = service.GetById(umbracoId);
            service.Delete(comment);
            commentService.Remove(id);

            return RedirectToUmbracoPage(parentId);

        }

    }
}

Vega/Vegumbr/Vegumbr/Views/Partials/_ArticlesPartial.cshtml
@using ContentModels = Umbraco.Web.PublishedContentModels;
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Article>
@{ 
    var truncateDescription = Umbraco.Truncate(@Model.Content.Description.ToString(), 70);
}

<div class="card container" style="margin-top:30px">
    <div class="card-body">
        <p>@Model.Content.Author</p>
        @truncateDescription
        <a style="margin-left:20px" href="@Model.Content.Url()" class="btn-danger btn pull-right">@Umbraco.GetDictionaryValue("Details")</a>
    </div>
</div>

Vega/Vegumbr/Vegumbr/Views/Partials/_CommentView.cshtml
@model Vegumbr.Models.CommentViewModel


<div id="afterPostMessage">

    @using (Ajax.BeginForm("Submit", "Comment", null, new AjaxOptions
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "afterPostMessage"
    }))
    {
        <div class="form-horizontal container">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <strong><label class="container">Leave your comment</label></strong>
                <div class="col-md-11">
                    @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.HiddenFor(model => model.PostId)
            @Html.HiddenFor(model => model.DocumentType)

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </div>
        </div>
    }
</div>

Vega/Vegumbr/Vegumbr/Views/Partials/_CommentsListPartial.cshtml
@model IEnumerable<Vegumbr.Models.CommentViewModel>
@using CustomRoleProvider = Vegumbr.Models.CustomRoleProvider;

@{
    var UserName = CustomRoleProvider.GetCurrentUser().First().ToString();

}

<div style="margin-top:30px">
    @foreach (var comment in Model)
    {
        <div class="card container">
            <div class="card-body">
                <strong>Author : @comment.Author</strong>
                <p>@comment.Message</p>
                @if (@comment.Author == UserName)
                {
                    @Html.ActionLink("Delete", "Delete", "Comment", new { @id = comment.Id, @parentId = comment.PostId, @umbracoId = comment.UmbracoId }, new { @class = "btn btn-primary" })
                }
            </div>
        </div>
    }
</div>

Vega/Vegumbr/Vegumbr/Views/Partials/_HeaderView.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using CustomRoleProvider = Vegumbr.Models.CustomRoleProvider;
@{
    ViewBag.Title = "_HeaderView";
    var UserName = CustomRoleProvider.GetCurrentUser().First().ToString();
    var siteRoot = Umbraco.Content(1098);
}


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Vega</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="btn btn-dark" href="/umbraco">Umbraco<span class="sr-only">(current)</span></a>

            @foreach (var navItem in siteRoot.Children)

            {
                if (@navItem.GetPropertyValue("showInNavigationMenu"))
                {
                    <a class="btn btn-dark ml-1" href="/@navItem.Name">@navItem.Name<span class="sr-only">(current)</span></a>
                }
            }
        </div>
    </div>
    <div>
        <strong class="mr-1">Hello, @UserName</strong>
        @if (UserName == "Guest")
        {
            <a class="btn btn-dark" href="/blogs/login/">Log In<span class="sr-only">(current)</span></a>
            <a class="btn btn-dark" href="http://localhost:5000/account/register">Register<span class="sr-only">(current)</span></a>
        }
        @if (UserName == "Guest")
        {
        }
        else
        {
            <a href="http://localhost:5000/Account/Logout" class="btn btn-info">Log out</a>
        }
    </div>
</nav>

Vega/Vegumbr/Vegumbr/Views/Partials/_MacroPostPartialView.cshtml
@using ContentModels = Umbraco.Web.PublishedContentModels;
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Blog>

@{
    var photoSource = Model.Content.MediaPhoto;
    var truncateDescription = @Umbraco.Truncate(Model.Content.Description.ToString(), 80);
}

<div class="card" style="width: 20rem; text-align:center; display:inline-block; margin-left:230px;margin-top:30px">
    <div>
        @{
            if (photoSource != null)
            {
                <img src="@photoSource.Url" style="width:200px" />
            }
        }
    </div>
    <div class="card-block">
        <h4 class="card-title">@Model.Content.Author</h4>
        <p class="card-text">@truncateDescription</p>
        <a href="@Model.Content.Url()" class="btn btn-primary">@Umbraco.GetDictionaryValue("Show more")</a>
    </div>
</div>

Vega/Vegumbr/Vegumbr/Views/Partials/_ShortBlogView.cshtml
@using ContentModels = Umbraco.Web.PublishedContentModels;
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Blog>

@{
    var truncateDescription = @Umbraco.Truncate(Model.Content.Description.ToString(), 40);
    var photoSource = Model.Content.MediaPhoto;
}

<div class="container shadow p-3 mb-5 bg-white rounded" style="margin-top:30px">
    <div class="row">
        <div class="col-lg-9">
            <p>@Model.Content.Author</p>
            <p>@Model.Content.Topic</p>
            @foreach (var tag in Model.Content.Tags)
            {
                <b class="badge badge-secondary">@tag</b>
            }
            <p>@truncateDescription</p>
        </div>
        <div class="col-lg-3">
            @{
                if (photoSource != null)
                {
                    <img src="@photoSource.Url" style="width:200px" />
                }
            }
        </div>
        <a style="margin-left:20px" href="@Model.Content.Url()" class="btn-danger btn pull-right">@Umbraco.GetDictionaryValue("Details")</a>
    </div>
</div>

Vega/Vegumbr/Vegumbr/Views/Partials/_SuccessAlert.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
<div class="container">
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">@Umbraco.GetDictionaryValue("Well Done")</h4>
        <p>@Umbraco.GetDictionaryValue("Processing")</p>
    </div>
</div>

Vega/Vegumbr/Vegumbr/Views/Partials/_SuccessPostFromUI.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
<div class="container" style="margin-top:50px">
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">Well Done</h4>
        <h4>Our admins will review your post, and after it u will see it on our page. Have a good day!</h4>
    </div>
</div>

Vega/Vegumbr/Vegumbr/Views/Partials/_UnregisteredCommentPartial.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
<div class="container">
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">Log in, and then you'll have access to comment something</h4>
    </div>
</div>