Vega/Vegumbr/Vegumbr/Controllers/GridControllers/BlogsController.cs
using Lecoati.LeBlender.Extension.Controllers;
using Lecoati.LeBlender.Extension.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using Umbraco.Web;
using Vegumbr.Models;
using Umbraco.Core.Models;

namespace Vegumbr.Controllers.GridControllers
{
    public class BlogsController : LeBlenderController
    {
        public ActionResult Index(LeBlenderModel model)
        {
            LeBlenderValue properties = model.Items.First();


            var title = properties.GetValue<string>("blockTitle");
            var contentNodes = properties.GetValue<ICollection<IPublishedContent>>("multiNode");
            var buttonTitle = properties.GetValue<string>("buttonTitle");
            var buttonLink = properties.GetValue<string>("buttonLink");
            string _currentUserName = "";

            if (CustomRoleProvider.GetCurrentUser().ToArray().Count() != 0)
            {
                _currentUserName = CustomRoleProvider.GetCurrentUser().First().ToString();
            }

            var viewModel = new BlockGridModel()
            {
                Title = title,
                Content = contentNodes.Select(ToGridModel).ToList(),
                ButtonLink = buttonLink,
                ButtonName = buttonTitle,
                CurrentUserName = _currentUserName,
            };

            return View(viewModel);
        }

        private GridModel ToGridModel(IPublishedContent content)
        {
            return new GridModel
            {
                Author = content.GetPropertyValue<string>("author") ?? content.CreatorName,
                Topic = content.GetPropertyValue<string>("topic"),
                Description = StripHTML(content.GetPropertyValue<string>("description")),
                Photo = content.GetPropertyValue<IPublishedContent>("mediaPhoto"),
                Tags = content.GetPropertyValue<string[]>("tags"),
                Url = content.Url()
            };
        }

        private string StripHTML(string htmlString)
        {
            return Regex.Replace(htmlString, "<.*?>", String.Empty);
        }
    }
}

Vega/Vegumbr/Vegumbr/Controllers/PostController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Umbraco.Core.Services;
using Umbraco.Web;
using Umbraco.Web.Mvc;
using Vegumbr.Models;
using Vegumbr.Models.Posts;

namespace Vegumbr.Controllers
{
    public class PostController : SurfaceController
    {
        public const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/";

        [HttpGet]
        public ActionResult NewPostForm()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Submit(PostViewModel model)
        {
            CreateNewPost(model);

            return PartialView(PARTIAL_VIEW_FOLDER + "_SuccessPostFromUI.cshtml");
        }

        private void CreateNewPost(PostViewModel model)
        {
            var userName = CustomRoleProvider.GetCurrentUser().First().ToString();
            IContentService contentService = Services.ContentService;
            var publishDate = DateTime.Now;
            var content = contentService.CreateContent("PostFromUI", 1119, "blog");

            content.ReleaseDate = publishDate;
            content.CreateDate = publishDate;
            content.UpdateDate = publishDate;
            content.SetValue("author", userName);
            content.SetValue("description", model.Description);
            content.SetValue("topic", model.Topic);

            contentService.Save(content);
        }
    }
}

Vega/Vegumbr/Vegumbr/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

Vega/Vegumbr/Vegumbr/Views/Partials/Grid/Editors/Blogs.cshtml
@using Vegumbr.Models
@model Vegumbr.Models.BlockGridModel

<div class="container">
    <div class="container">
        <div style="float:right;margin-top:20px">
            @Html.ActionLink("Add new post", "NewPostForm", "Post", null, new { @class = "btn btn-primary" })
        </div>
    </div>
    @if (Model.Title != null)
    {
        <h1>@Model.Title</h1>
    }

    @foreach (var node in Model.Content)
    {
        @RenderBox(node);
    }

    @if (!String.IsNullOrWhiteSpace(Model.ButtonName)
        && !String.IsNullOrWhiteSpace(Model.ButtonLink))
    {
        <a href="@Model.ButtonLink" class="btn btn-primary">@Model.ButtonName</a>
    }
</div>

@helper RenderBox(GridModel item)
{
    var backgroundUrl = item.Photo == null
        ? "https://pbs.twimg.com/profile_images/1289241244/groupanon_400x400.png"
        : item.Photo.Url;

    <div class="shadow p-3 mb-5 bg-white rounded" style="margin-top:30px">
        <div class="row">
            <div class="col-lg-9">
                <p>@item.Author</p>
                <p>@item.Topic</p>
                @if (item.Tags != null)
                {
                    @RenderTags(item.Tags);
                }
                <p>@item.Description</p>
            </div>
            <div class="col-lg-3">
                <img src="@backgroundUrl" style="width:200px" />
            </div>
        </div>
        <a href="@item.Url" class="btn-danger btn pull-right">Details</a>
    </div>
}

@helper RenderTags(string[] items)
{
    foreach (var tag in items)
    {
        <b class="badge badge-secondary">@tag</b>
    }
}

Vega/Vegumbr/Vegumbr/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates


<div class="video-wrapper">
	@Html.Raw(Model.value)
</div>

Vega/Vegumbr/Vegumbr/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

Vega/Vegumbr/Vegumbr/Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.value != null)
{   
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        url += "?width=" + Model.editor.config.size.width;
        url += "&height=" + Model.editor.config.size.height;

        if(Model.value.focalPoint != null){
            url += "&center=" + Model.value.focalPoint.top +"," + Model.value.focalPoint.left;
            url += "&mode=crop";
        }
    }

    var altText = Model.value.altText ?? Model.value.caption ?? string.Empty;
    
    <img src="@url" alt="@altText">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

Vega/Vegumbr/Vegumbr/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))

Vega/Vegumbr/Vegumbr/Views/Partials/Grid/Editors/Textstring.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.editor.config.markup != null)
{
    string markup = Model.editor.config.markup.ToString();
    var umbracoHelper = new UmbracoHelper(UmbracoContext.Current);
    markup = markup.Replace("#value#", umbracoHelper.ReplaceLineBreaksForHtml(HttpUtility.HtmlEncode(Model.value.ToString())));
    
    if (Model.editor.config.style != null)
    {
        markup = markup.Replace("#style#", Model.editor.config.style.ToString());
    }

    <text>
        @Html.Raw(markup)
    </text>
}
else
{
    <text>
        <div style="@Model.editor.config.style">@Model.value</div>
    </text>
}